### ISSUE TITLE
Remove chain sync based features

### ISSUE THREAD

**Issue by ardevd** [ardevd/ha-bobcatminer#10]
Bobcat miners are now updated with firmware that removes chain syncing completely. Hence, there is no longer need for chain sync related sensors.

**Comment by Hatfa** [comment]
Something has also changed regarding the temperature sensor. I couldn't get it to work properly.

**Comment by ardevd** [comment]
Temperature reporting works fine here. Can you elaborate on your issue?

**Comment by Hatfa** [comment]
> Temperature reporting works fine here. Can you elaborate on your issue?

I'm not sure what happened but the entity was unavailable after the update, along with the sync stuff obviously. I have removed and reinstalled the integration but it didn't fix the issue. 
After your latest update that got fixed so whatever you have done, thank you 😁
