### ISSUE TITLE
how can we install this in HACS

### ISSUE THREAD

**Issue by TrueIntelligence** [ardevd/ha-bobcatminer#28]
how can we install this in HACS

**Comment by ardevd** [comment]
Simply install HACS, then search for "Bobcat Miner" and install.

**Comment by TrueIntelligence** [comment]
It’s asking for a server



We need more information please

- Thank You

*Confidentiality Notice:  This email and any files attached may contain
confidential information that is legally privileged.  If you are not the
intended recipient, or a person responsible for delivering it, you are
hereby notified that any disclosure, copying, distribution or use of any of
the information contained in or attached to this transmission is strictly
prohibited and punishable under penalty of **perjury..If you have received
this transmission in error, please destroy the original transmission and
its attachments without reading or saving in any manner.*

**Comment by ardevd** [comment]
What's asking for a server exactly? Have you properly installed HACS? Have you managed to install the Bobcat Miner component through HACS?

**Comment by TrueIntelligence** [comment]
HACs the iphone app is asking for a server , do you have a link to HACs?




- Thank You

*Confidentiality Notice:  This email and any files attached may contain
confidential information that is legally privileged.  If you are not the
intended recipient, or a person responsible for delivering it, you are
hereby notified that any disclosure, copying, distribution or use of any of
the information contained in or attached to this transmission is strictly
prohibited and punishable under penalty of **perjury..If you have received
this transmission in error, please destroy the original transmission and
its attachments without reading or saving in any manner.*

**Comment by ardevd** [comment]
You're most likely not interacting with the correct HACS.

https://hacs.xyz

**Comment by TrueIntelligence** [comment]
I see , it looks like it will need its own server and its complicated to
install

- Thank You

*Confidentiality Notice:  This email and any files attached may contain
confidential information that is legally privileged.  If you are not the
intended recipient, or a person responsible for delivering it, you are
hereby notified that any disclosure, copying, distribution or use of any of
the information contained in or attached to this transmission is strictly
prohibited and punishable under penalty of **perjury..If you have received
this transmission in error, please destroy the original transmission and
its attachments without reading or saving in any manner.*

**Comment by ardevd** [comment]
Well, this is a component for Home Assistant so if you don't have Home Assistant you could use bobcatpy directly if you want. https://github.com/ardevd/bobcatpy

**Comment by TrueIntelligence** [comment]
Thanks, I'll check it out.
