### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by ItsJamesMurray** [ardevd/ha-bobcatminer#31]
Hello!

I installed the integration via HACS.  I went to add an integration and searched for "Bobcat Miner".  I click the name and then receive a popup saying:

```
ERROR
Config flow could not be loaded: {"message":"Invalid handler specified"}
```

**Comment by ardevd** [comment]
Hmm, so you're saying you can't install it via HACS or you can't set up the integration after HACS installation?

**Comment by ItsJamesMurray** [comment]
It was after the HACS install.  I restarted the docker container running HA and it still did not work.  Restarted my server and the docker container running HA.  Must have been something odd/off on my end.  Apologies!
