### ISSUE TITLE
No more updated data after a few hours

### ISSUE THREAD

**Issue by J-Bot87** [ardevd/ha-bobcatminer#7]
Hello,

Thank you for your work and sharing !

After few hours, plugin no  longer update data, I have to restart my home assitsant server and it starts again.

Platform : Intel NUC i3, Vmware Esxi, Hassio OS (version : 5.10.108)
Home assistant version : 2022.4.3
Bobcat is wired connected

![bobcat-hassio](https://user-images.githubusercontent.com/85930806/163536824-e1aa6f70-7fae-4151-b219-de933230ad34.jpg)

**Comment by ardevd** [comment]
Thanks for reporting the issue. I'm aware of it and it's caused by the integration crashing when it fails to access the miner. I'll add some improved exception handling which should fix the problem.

**Comment by J-Bot87** [comment]
> Thanks for reporting the issue. I'm aware of it and it's caused by the integration crashing when it fails to access the miner. I'll add some improved exception handling which should fix the problem. 

Great ! Thanks ! 
It's an awesome tool to supervise bobcat

**Comment by ardevd** [comment]
Fixed (hopefully) with cd29ecd2739548e5f5ebea4ad35f6e695ccb5b24
