### ISSUE TITLE
Feature Request - Alternative Miner Integration?

### ISSUE THREAD

**Issue by JackPala** [ardevd/ha-bobcatminer#9]
Looks cool, sadly cannot use because I don't use the Bobcat Platform - But seems like data would be pretty brand agnostic since all Helium miner's have to meet some pretty strict standardization to be operable. With that said, are there any plans at this time to widen the scope of acceptable miners for this plugin? Or perhaps pull directly from the Helium central Web API on their website? Willing to fork if not. That said, project looks cool.

**Comment by ardevd** [comment]
Unfortunately, this integration relies heavily on the Bobcat-specific web diagnoser. Several other miner OEMs have implemented their own, but totally different equivalents.

You could develop something similar based on the Helium explorer API but the data there is so delayed that the usefulness might be questionable. 

That said, this integration really only needs a standardized json output from an underlying library. I've developed `bobcatpy` which does exactly that and if one were to develop something for other miner OEMs then I'd be very happy to add them to this integration. That would probably mean rebranding this integration as it would no longer be Bobcat specific :)
